// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: base_node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                // Unique ID for the Super Node
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`                              // Region where node operates
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`                                      // Reachable public IP
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`       // Base64(Ed25519 public key)
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                        // Base64(Ed25519 signature of ID+region+ip+nonce)
	Nonce         string                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`                                // Base64 random nonce
	MaxPeers      int32                  `protobuf:"varint,7,opt,name=max_peers,json=maxPeers,proto3" json:"max_peers,omitempty"`         // Config limit
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`                            // Software version
	StartupTime   string                 `protobuf:"bytes,9,opt,name=startup_time,json=startupTime,proto3" json:"startup_time,omitempty"` // ISO 8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_base_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_base_node_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RegisterRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *RegisterRequest) GetMaxPeers() int32 {
	if x != nil {
		return x.MaxPeers
	}
	return 0
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetStartupTime() string {
	if x != nil {
		return x.StartupTime
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedId    string                 `protobuf:"bytes,3,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_base_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_base_node_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

func (x *RegisterResponse) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type HeartbeatRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActivePeers        int32                  `protobuf:"varint,2,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`
	ExitPeersAvailable int32                  `protobuf:"varint,3,opt,name=exit_peers_available,json=exitPeersAvailable,proto3" json:"exit_peers_available,omitempty"`
	AvgLatencyMs       float32                `protobuf:"fixed32,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	BandwidthUsageMbps float32                `protobuf:"fixed32,5,opt,name=bandwidth_usage_mbps,json=bandwidthUsageMbps,proto3" json:"bandwidth_usage_mbps,omitempty"`
	Timestamp          string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_base_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_base_node_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetActivePeers() int32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

func (x *HeartbeatRequest) GetExitPeersAvailable() int32 {
	if x != nil {
		return x.ExitPeersAvailable
	}
	return 0
}

func (x *HeartbeatRequest) GetAvgLatencyMs() float32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *HeartbeatRequest) GetBandwidthUsageMbps() float32 {
	if x != nil {
		return x.BandwidthUsageMbps
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_base_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_base_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_base_node_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_base_node_proto protoreflect.FileDescriptor

const file_base_node_proto_rawDesc = "" +
	"\n" +
	"\x0fbase_node.proto\x12\x04dvpn\"\xff\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\x12\x1b\n" +
	"\tmax_peers\x18\a \x01(\x05R\bmaxPeers\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12!\n" +
	"\fstartup_time\x18\t \x01(\tR\vstartupTime\"\x8c\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vassigned_id\x18\x03 \x01(\tR\n" +
	"assignedId\x12#\n" +
	"\rregistered_at\x18\x04 \x01(\tR\fregisteredAt\"\xf6\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\factive_peers\x18\x02 \x01(\x05R\vactivePeers\x120\n" +
	"\x14exit_peers_available\x18\x03 \x01(\x05R\x12exitPeersAvailable\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x02R\favgLatencyMs\x120\n" +
	"\x14bandwidth_usage_mbps\x18\x05 \x01(\x02R\x12bandwidthUsageMbps\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\";\n" +
	"\x03Ack\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8e\x01\n" +
	"\x0fBaseNodeService\x12B\n" +
	"\x11RegisterSuperNode\x12\x15.dvpn.RegisterRequest\x1a\x16.dvpn.RegisterResponse\x127\n" +
	"\x12SuperNodeHeartbeat\x12\x16.dvpn.HeartbeatRequest\x1a\t.dvpn.AckB&Z$github.com/vairabarath/Dvpn/super/pbb\x06proto3"

var (
	file_base_node_proto_rawDescOnce sync.Once
	file_base_node_proto_rawDescData []byte
)

func file_base_node_proto_rawDescGZIP() []byte {
	file_base_node_proto_rawDescOnce.Do(func() {
		file_base_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_node_proto_rawDesc), len(file_base_node_proto_rawDesc)))
	})
	return file_base_node_proto_rawDescData
}

var file_base_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_base_node_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: dvpn.RegisterRequest
	(*RegisterResponse)(nil), // 1: dvpn.RegisterResponse
	(*HeartbeatRequest)(nil), // 2: dvpn.HeartbeatRequest
	(*Ack)(nil),              // 3: dvpn.Ack
}
var file_base_node_proto_depIdxs = []int32{
	0, // 0: dvpn.BaseNodeService.RegisterSuperNode:input_type -> dvpn.RegisterRequest
	2, // 1: dvpn.BaseNodeService.SuperNodeHeartbeat:input_type -> dvpn.HeartbeatRequest
	1, // 2: dvpn.BaseNodeService.RegisterSuperNode:output_type -> dvpn.RegisterResponse
	3, // 3: dvpn.BaseNodeService.SuperNodeHeartbeat:output_type -> dvpn.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_node_proto_init() }
func file_base_node_proto_init() {
	if File_base_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_node_proto_rawDesc), len(file_base_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_node_proto_goTypes,
		DependencyIndexes: file_base_node_proto_depIdxs,
		MessageInfos:      file_base_node_proto_msgTypes,
	}.Build()
	File_base_node_proto = out.File
	file_base_node_proto_goTypes = nil
	file_base_node_proto_depIdxs = nil
}
