// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: exit_peer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExitPeerInfoRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequesterId      string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	ClientPublicKey  string                 `protobuf:"bytes,2,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	MinBandwidthMbps float32                `protobuf:"fixed32,3,opt,name=min_bandwidth_mbps,json=minBandwidthMbps,proto3" json:"min_bandwidth_mbps,omitempty"`
	MaxLatencyMs     float32                `protobuf:"fixed32,4,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	Region           string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExitPeerInfoRequest) Reset() {
	*x = ExitPeerInfoRequest{}
	mi := &file_exit_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitPeerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitPeerInfoRequest) ProtoMessage() {}

func (x *ExitPeerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exit_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitPeerInfoRequest.ProtoReflect.Descriptor instead.
func (*ExitPeerInfoRequest) Descriptor() ([]byte, []int) {
	return file_exit_peer_proto_rawDescGZIP(), []int{0}
}

func (x *ExitPeerInfoRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *ExitPeerInfoRequest) GetClientPublicKey() string {
	if x != nil {
		return x.ClientPublicKey
	}
	return ""
}

func (x *ExitPeerInfoRequest) GetMinBandwidthMbps() float32 {
	if x != nil {
		return x.MinBandwidthMbps
	}
	return 0
}

func (x *ExitPeerInfoRequest) GetMaxLatencyMs() float32 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

func (x *ExitPeerInfoRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ExitPeerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	EndpointIp    string                 `protobuf:"bytes,2,opt,name=endpoint_ip,json=endpointIp,proto3" json:"endpoint_ip,omitempty"`
	EndpointPort  string                 `protobuf:"bytes,3,opt,name=endpoint_port,json=endpointPort,proto3" json:"endpoint_port,omitempty"`
	AllowedIps    string                 `protobuf:"bytes,4,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	BandwidthMbps float32                `protobuf:"fixed32,5,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"`
	LatencyMs     float32                `protobuf:"fixed32,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ClientIp      string                 `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitPeerInfoResponse) Reset() {
	*x = ExitPeerInfoResponse{}
	mi := &file_exit_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitPeerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitPeerInfoResponse) ProtoMessage() {}

func (x *ExitPeerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exit_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitPeerInfoResponse.ProtoReflect.Descriptor instead.
func (*ExitPeerInfoResponse) Descriptor() ([]byte, []int) {
	return file_exit_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ExitPeerInfoResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ExitPeerInfoResponse) GetEndpointIp() string {
	if x != nil {
		return x.EndpointIp
	}
	return ""
}

func (x *ExitPeerInfoResponse) GetEndpointPort() string {
	if x != nil {
		return x.EndpointPort
	}
	return ""
}

func (x *ExitPeerInfoResponse) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *ExitPeerInfoResponse) GetBandwidthMbps() float32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *ExitPeerInfoResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ExitPeerInfoResponse) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

var File_exit_peer_proto protoreflect.FileDescriptor

const file_exit_peer_proto_rawDesc = "" +
	"\n" +
	"\x0fexit_peer.proto\x12\x04dvpn\"\xd0\x01\n" +
	"\x13ExitPeerInfoRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12*\n" +
	"\x11client_public_key\x18\x02 \x01(\tR\x0fclientPublicKey\x12,\n" +
	"\x12min_bandwidth_mbps\x18\x03 \x01(\x02R\x10minBandwidthMbps\x12$\n" +
	"\x0emax_latency_ms\x18\x04 \x01(\x02R\fmaxLatencyMs\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\"\xff\x01\n" +
	"\x14ExitPeerInfoResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vendpoint_ip\x18\x02 \x01(\tR\n" +
	"endpointIp\x12#\n" +
	"\rendpoint_port\x18\x03 \x01(\tR\fendpointPort\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x01(\tR\n" +
	"allowedIps\x12%\n" +
	"\x0ebandwidth_mbps\x18\x05 \x01(\x02R\rbandwidthMbps\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x02R\tlatencyMs\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp2\\\n" +
	"\x0fExitPeerService\x12I\n" +
	"\x10GetWireGuardInfo\x12\x19.dvpn.ExitPeerInfoRequest\x1a\x1a.dvpn.ExitPeerInfoResponseB\x10Z\x0eClient_peer/pbb\x06proto3"

var (
	file_exit_peer_proto_rawDescOnce sync.Once
	file_exit_peer_proto_rawDescData []byte
)

func file_exit_peer_proto_rawDescGZIP() []byte {
	file_exit_peer_proto_rawDescOnce.Do(func() {
		file_exit_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exit_peer_proto_rawDesc), len(file_exit_peer_proto_rawDesc)))
	})
	return file_exit_peer_proto_rawDescData
}

var file_exit_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exit_peer_proto_goTypes = []any{
	(*ExitPeerInfoRequest)(nil),  // 0: dvpn.ExitPeerInfoRequest
	(*ExitPeerInfoResponse)(nil), // 1: dvpn.ExitPeerInfoResponse
}
var file_exit_peer_proto_depIdxs = []int32{
	0, // 0: dvpn.ExitPeerService.GetWireGuardInfo:input_type -> dvpn.ExitPeerInfoRequest
	1, // 1: dvpn.ExitPeerService.GetWireGuardInfo:output_type -> dvpn.ExitPeerInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exit_peer_proto_init() }
func file_exit_peer_proto_init() {
	if File_exit_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exit_peer_proto_rawDesc), len(file_exit_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exit_peer_proto_goTypes,
		DependencyIndexes: file_exit_peer_proto_depIdxs,
		MessageInfos:      file_exit_peer_proto_msgTypes,
	}.Build()
	File_exit_peer_proto = out.File
	file_exit_peer_proto_goTypes = nil
	file_exit_peer_proto_depIdxs = nil
}
