// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: super_node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	NatType       string                 `protobuf:"bytes,6,opt,name=nat_type,json=natType,proto3" json:"nat_type,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	Nonce         string                 `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRegistrationRequest) Reset() {
	*x = PeerRegistrationRequest{}
	mi := &file_super_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRegistrationRequest) ProtoMessage() {}

func (x *PeerRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_super_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRegistrationRequest.ProtoReflect.Descriptor instead.
func (*PeerRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_super_node_proto_rawDescGZIP(), []int{0}
}

func (x *PeerRegistrationRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerRegistrationRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerRegistrationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerRegistrationRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *PeerRegistrationRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PeerRegistrationRequest) GetNatType() string {
	if x != nil {
		return x.NatType
	}
	return ""
}

func (x *PeerRegistrationRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *PeerRegistrationRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type PeerSessionHeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeerId            string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ExitPeerId        string                 `protobuf:"bytes,2,opt,name=exit_peer_id,json=exitPeerId,proto3" json:"exit_peer_id,omitempty"`
	LatencyMs         int32                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	PacketLoss        float32                `protobuf:"fixed32,4,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	ThroughputMbps    float32                `protobuf:"fixed32,5,opt,name=throughput_mbps,json=throughputMbps,proto3" json:"throughput_mbps,omitempty"`
	SessionUptimeSecs int32                  `protobuf:"varint,6,opt,name=session_uptime_secs,json=sessionUptimeSecs,proto3" json:"session_uptime_secs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerSessionHeartbeatRequest) Reset() {
	*x = PeerSessionHeartbeatRequest{}
	mi := &file_super_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSessionHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSessionHeartbeatRequest) ProtoMessage() {}

func (x *PeerSessionHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_super_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSessionHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*PeerSessionHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_super_node_proto_rawDescGZIP(), []int{1}
}

func (x *PeerSessionHeartbeatRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerSessionHeartbeatRequest) GetExitPeerId() string {
	if x != nil {
		return x.ExitPeerId
	}
	return ""
}

func (x *PeerSessionHeartbeatRequest) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PeerSessionHeartbeatRequest) GetPacketLoss() float32 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *PeerSessionHeartbeatRequest) GetThroughputMbps() float32 {
	if x != nil {
		return x.ThroughputMbps
	}
	return 0
}

func (x *PeerSessionHeartbeatRequest) GetSessionUptimeSecs() int32 {
	if x != nil {
		return x.SessionUptimeSecs
	}
	return 0
}

var File_super_node_proto protoreflect.FileDescriptor

const file_super_node_proto_rawDesc = "" +
	"\n" +
	"\x10super_node.proto\x12\x04dvpn\x1a\x0fbase_node.proto\"\xe2\x01\n" +
	"\x17PeerRegistrationRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x19\n" +
	"\bnat_type\x18\x06 \x01(\tR\anatType\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12\x14\n" +
	"\x05nonce\x18\b \x01(\tR\x05nonce\"\xf1\x01\n" +
	"\x1bPeerSessionHeartbeatRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12 \n" +
	"\fexit_peer_id\x18\x02 \x01(\tR\n" +
	"exitPeerId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x05R\tlatencyMs\x12\x1f\n" +
	"\vpacket_loss\x18\x04 \x01(\x02R\n" +
	"packetLoss\x12'\n" +
	"\x0fthroughput_mbps\x18\x05 \x01(\x02R\x0ethroughputMbps\x12.\n" +
	"\x13session_uptime_secs\x18\x06 \x01(\x05R\x11sessionUptimeSecs2\xa5\x01\n" +
	"\x10SuperNodeService\x12K\n" +
	"\x12RegisterClientPeer\x12\x1d.dvpn.PeerRegistrationRequest\x1a\x16.dvpn.RegisterResponse\x12D\n" +
	"\x14PeerSessionHeartbeat\x12!.dvpn.PeerSessionHeartbeatRequest\x1a\t.dvpn.AckB&Z$github.com/vairabarath/Dvpn/super/pbb\x06proto3"

var (
	file_super_node_proto_rawDescOnce sync.Once
	file_super_node_proto_rawDescData []byte
)

func file_super_node_proto_rawDescGZIP() []byte {
	file_super_node_proto_rawDescOnce.Do(func() {
		file_super_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_super_node_proto_rawDesc), len(file_super_node_proto_rawDesc)))
	})
	return file_super_node_proto_rawDescData
}

var file_super_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_super_node_proto_goTypes = []any{
	(*PeerRegistrationRequest)(nil),     // 0: dvpn.PeerRegistrationRequest
	(*PeerSessionHeartbeatRequest)(nil), // 1: dvpn.PeerSessionHeartbeatRequest
	(*RegisterResponse)(nil),            // 2: dvpn.RegisterResponse
	(*Ack)(nil),                         // 3: dvpn.Ack
}
var file_super_node_proto_depIdxs = []int32{
	0, // 0: dvpn.SuperNodeService.RegisterClientPeer:input_type -> dvpn.PeerRegistrationRequest
	1, // 1: dvpn.SuperNodeService.PeerSessionHeartbeat:input_type -> dvpn.PeerSessionHeartbeatRequest
	2, // 2: dvpn.SuperNodeService.RegisterClientPeer:output_type -> dvpn.RegisterResponse
	3, // 3: dvpn.SuperNodeService.PeerSessionHeartbeat:output_type -> dvpn.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_super_node_proto_init() }
func file_super_node_proto_init() {
	if File_super_node_proto != nil {
		return
	}
	file_base_node_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_super_node_proto_rawDesc), len(file_super_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_super_node_proto_goTypes,
		DependencyIndexes: file_super_node_proto_depIdxs,
		MessageInfos:      file_super_node_proto_msgTypes,
	}.Build()
	File_super_node_proto = out.File
	file_super_node_proto_goTypes = nil
	file_super_node_proto_depIdxs = nil
}
