// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: base_sync.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseFederationService_RequestRemoteSuperNodes_FullMethodName = "/dvpn.BaseFederationService/RequestRemoteSuperNodes"
)

// BaseFederationServiceClient is the client API for BaseFederationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseFederationServiceClient interface {
	RequestRemoteSuperNodes(ctx context.Context, in *RemoteSuperRequest, opts ...grpc.CallOption) (*RemoteSuperResponse, error)
}

type baseFederationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseFederationServiceClient(cc grpc.ClientConnInterface) BaseFederationServiceClient {
	return &baseFederationServiceClient{cc}
}

func (c *baseFederationServiceClient) RequestRemoteSuperNodes(ctx context.Context, in *RemoteSuperRequest, opts ...grpc.CallOption) (*RemoteSuperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoteSuperResponse)
	err := c.cc.Invoke(ctx, BaseFederationService_RequestRemoteSuperNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseFederationServiceServer is the server API for BaseFederationService service.
// All implementations must embed UnimplementedBaseFederationServiceServer
// for forward compatibility.
type BaseFederationServiceServer interface {
	RequestRemoteSuperNodes(context.Context, *RemoteSuperRequest) (*RemoteSuperResponse, error)
	mustEmbedUnimplementedBaseFederationServiceServer()
}

// UnimplementedBaseFederationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseFederationServiceServer struct{}

func (UnimplementedBaseFederationServiceServer) RequestRemoteSuperNodes(context.Context, *RemoteSuperRequest) (*RemoteSuperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRemoteSuperNodes not implemented")
}
func (UnimplementedBaseFederationServiceServer) mustEmbedUnimplementedBaseFederationServiceServer() {}
func (UnimplementedBaseFederationServiceServer) testEmbeddedByValue()                               {}

// UnsafeBaseFederationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseFederationServiceServer will
// result in compilation errors.
type UnsafeBaseFederationServiceServer interface {
	mustEmbedUnimplementedBaseFederationServiceServer()
}

func RegisterBaseFederationServiceServer(s grpc.ServiceRegistrar, srv BaseFederationServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseFederationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseFederationService_ServiceDesc, srv)
}

func _BaseFederationService_RequestRemoteSuperNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteSuperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseFederationServiceServer).RequestRemoteSuperNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseFederationService_RequestRemoteSuperNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseFederationServiceServer).RequestRemoteSuperNodes(ctx, req.(*RemoteSuperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseFederationService_ServiceDesc is the grpc.ServiceDesc for BaseFederationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseFederationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dvpn.BaseFederationService",
	HandlerType: (*BaseFederationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRemoteSuperNodes",
			Handler:    _BaseFederationService_RequestRemoteSuperNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base_sync.proto",
}
